import { FieldType } from "@/@types/index.type";
import { carBrands } from "./cars";

export const addListingFields: FieldType[] = [
  {
    name: "brand",
    fieldType: "select",
    label: "Brand (Make)",
    value: "",
    required: true,
    disabled: false,
    options: carBrands,
  },
  {
    name: "model",
    fieldType: "text",
    label: "Model",
    value: "",
    required: true,
    disabled: false,
  },
  {
    name: "yearOfManufacture",
    fieldType: "number",
    label: "Year of Manufacture",
    value: "",
    required: true,
    disabled: false,
  },
  {
    name: "exteriorColor",
    fieldType: "text",
    label: "Exterior Color",
    value: "",
    required: true,
    disabled: false,
  },
  {
    name: "interiorColor",
    fieldType: "text",
    label: "Interior Color",
    value: "",
    required: false,
    disabled: false,
  },
  {
    name: "condition",
    fieldType: "select",
    label: "Condition",
    value: "",
    required: true,
    disabled: false,
    options: [
      { value: "brandNew", label: "Brand New" },
      { value: "used", label: "Used" },
    ],
  },
  {
    name: "secondCondition",
    fieldType: "multiselect",
    label: "Second Condition (Optional)",
    value: [],
    required: false,
    disabled: false,
    options: [
      { value: "afterCrash", label: "After Crash" },
      { value: "engineIssue", label: "Engine Issue" },
      { value: "gearIssue", label: "Gear Issue" },
      { value: "needBodyRepair", label: "Needs Body Repair" },
      { value: "needRepair", label: "Needs Repair" },
      { value: "needRepainting", label: "Needs Repainting" },
      { value: "tireDamage", label: "Tire Damage" },
      { value: "glassDamage", label: "Glass Damage" },
      { value: "electricalIssue", label: "Electrical Issue" },
      { value: "suspensionIssue", label: "Suspension Issue" },
      { value: "brakeIssue", label: "Brake Issue" },
      { value: "interiorDamage", label: "Interior Damage" },
      { value: "minorWearTear", label: "Minor Wear and Tear" },
    ],
  },
  {
    name: "mileage",
    fieldType: "number",
    label: "Mileage (KM)",
    value: "",
    required: false,
    disabled: false,
  },
  {
    name: "transmission",
    fieldType: "select",
    label: "Transmission",
    value: "",
    required: true,
    disabled: false,
    options: [
      { value: "automatic", label: "Automatic" },
      { value: "manual", label: "Manual" },
      { value: "cvt", label: "CVT" },
      { value: "amt", label: "AMT" },
    ],
  },
  {
    name: "fuelType",
    fieldType: "select",
    label: "Fuel Type",
    value: "",
    required: true,
    disabled: false,
    options: [
      { value: "gasoline", label: "Gasoline" },
      { value: "diesel", label: "Diesel" },
      { value: "electric", label: "Electric" },
      { value: "hybrid", label: "Hybrid" },
    ],
  },
  {
    name: "keyFeatures",
    fieldType: "multiselect",
    label: "Key Features (Optional)",
    value: [],
    required: false,
    disabled: false,
    options: [
      { value: "sunroof", label: "Sunroof/Moonroof" },
      { value: "navigation", label: "Navigation System" },
      { value: "leatherSeats", label: "Leather Seats" },
      { value: "heatedSeats", label: "Heated Seats" },
      { value: "cooledSeats", label: "Cooled Seats (Ventilated)" },
      { value: "powerSeats", label: "Power Seats" },
      { value: "memorySeats", label: "Memory Seats" },
      { value: "premiumSound", label: "Premium Sound System" },
      { value: "alloyWheels", label: "Alloy Wheels" },
      { value: "parkingSensors", label: "Parking Sensors" },
      { value: "rearviewCamera", label: "Rearview Camera" },
      { value: "360Camera", label: "360° Camera" },
      { value: "blindSpotMonitor", label: "Blind Spot Monitor" },
      { value: "laneDepartureWarning", label: "Lane Departure Warning" },
      { value: "adaptiveCruiseControl", label: "Adaptive Cruise Control" },
      {
        value: "automaticEmergencyBraking",
        label: "Automatic Emergency Braking",
      },
      { value: "bluetooth", label: "Bluetooth Connectivity" },
      { value: "appleCarplay", label: "Apple CarPlay" },
      { value: "androidAuto", label: "Android Auto" },
      { value: "keylessEntry", label: "Keyless Entry" },
      { value: "pushButtonStart", label: "Push Button Start" },
      { value: "remoteStart", label: "Remote Start" },
      { value: "powerWindows", label: "Power Windows" },
      { value: "powerLocks", label: "Power Locks" },
      { value: "airConditioning", label: "Air Conditioning" },
      { value: "dualZoneClimateControl", label: "Dual-Zone Climate Control" },
    ],
  },

  {
    name: "vin",
    fieldType: "text",
    label: "VIN Chassis Number",
    value: "",
    required: false,
  },
  {
    name: "bodyType",
    fieldType: "select",
    label: "Body Type",
    value: "",
    required: false,
    disabled: false,
    options: [
      { value: "sedan", label: "Sedan" },
      { value: "suv", label: "SUV" },
      { value: "truck", label: "Truck" },
      { value: "hatchback", label: "Hatchback" },
      { value: "coupe", label: "Coupe" },
      { value: "convertible", label: "Convertible" },
      { value: "van", label: "Van/Minivan" },
      { value: "wagon", label: "Wagon" },
      { value: "other", label: "Other" },
    ],
  },

  {
    name: "drivetrain",
    fieldType: "select",
    label: "Drivetrain",
    value: "",
    required: true,
    disabled: false,
    options: [
      { value: "fwd", label: "Front-Wheel Drive (FWD)" },
      { value: "rwd", label: "Rear-Wheel Drive (RWD)" },
      { value: "awd", label: "All-Wheel Drive (AWD)" },
      { value: "4wd", label: "Four-Wheel Drive (4WD)" },
    ],
  },
  {
    name: "seatingCapacity",
    fieldType: "number",
    label: "Seating Capacity",
    value: "",
    required: false,
    disabled: false,
  },
  {
    name: "description",
    fieldType: "textarea",
    label: "Description",
    value: "",
    col: 2,
    required: false,
    disabled: false,
  },
  {
    name: "price",
    fieldType: "number",
    label: "Price",
    value: "",
    col: 2,
    required: true,
    disabled: false,
  },

  {
    name: "carTitle",
    fieldType: "text",
    label: "Car Title",
    value: "",
    required: false,
    disabled: true,
  },
  {
    name: "contactPhone",
    fieldType: "text",
    label: "Contact Phone Number",
    value: "",
    required: false,
    disabled: false,
  },
];
